### PR TITLE
Added benchmarks from AWS NSym (Arm Symbolic Simulator)

### PR DESCRIPTION
**Pull request by nwetzler**
We have included some benchmarks produced by NSym, our symbolic simulator for Arm assembly code. The problems fit into two categories. The first are the raw benchmarks produced by the simulator, many of which are unknown by current solvers. The second are the problems after some manual and automated rewriting which makes the problems much easier to solve. We hope this will help motivate the community to identify opportunities to improve machine-code proofs via SMT.

Courtesy of Amazon Web Services - Automated Reasoning Group - Low Level Code Reasoning Team.

### CODE REVIEW

**Comment by hansjoergschurr** [comment]
Those benchmarks look great!  One suggestion I have is to change `Application` field in the header.  Right now it seems the header contains the benchmark name.  Usually, this field is used for a short description of the problem domain of the benchmark.
In your case I think something like "Symbolic simulation of ARM assembly code" would work well.
What do you think?

A tiny other edit I would do is to add a line beak after the `|` at the start of the `:source` header.

**Comment by nwetzler** [comment]
> Those benchmarks look great! One suggestion I have is to change `Application` field in the header. Right now it seems the header contains the benchmark name. Usually, this field is used for a short description of the problem domain of the benchmark. In your case I think something like "Symbolic simulation of ARM assembly code" would work well. What do you think?
> 
> A tiny other edit I would do is to add a line beak after the `|` at the start of the `:source` header.

Will do.

**Comment by nwetzler** [comment]
Updated Application field and fixed spacing.

**Comment by hansjoergschurr** [comment]
Looks great! I will merge the benchmarks now.  Before adding them to the release we will do some more tests, like short solver runs to find mistyped `:status` entries.

Thank you very much for the contribution.

**Pull request merged**
