### PR TITLE
Benchmarks for redos attack detections

### PR DESCRIPTION
**Pull request by SimpleXiaohu**
The dataset is generated by the tool ReDoSHunter4SymExec
 at https://github.com/SuperMaxine/ReDoSHunter4SymExec, to test whether attacks for a regular expression exist.  
Target solver: Ostrich, Z3str3, CVC5

### CODE REVIEW

**Comment by hansjoergschurr** [comment]
It looks like your pull request does not add any benchmarks (it only removes the ones that are already in the repository)

**Comment by SimpleXiaohu** [comment]
> It looks like your pull request does not add any benchmarks (it only removes the ones that are already in the repository)
Sorry about that, I have updated the bench.

**Comment by hansjoergschurr** [comment]
It seems like the problem is still there.  Maybe you forgot or mistyped the `git add` to add the new files?

If you want you can also send the benchmarks via email to `hansjoerg-schurr@uiowa.edu`.

**Comment by SimpleXiaohu** [comment]
Thanks for pointing it out. I forgot to add the new bench after updating it. It will work now.

**Comment by hansjoergschurr** [comment]
I took the liberty to fix some small things in the benchmarks. I also removed duplicates.  I think you can pull my changes into your branch.

Now the basic checks pass, but Dolmen shows an error for at least one file: `re.++` expects at least two arguments.

Can you have a look and see if  you could fix this?  Likely you need to remove the `re.++`.

**Comment by SimpleXiaohu** [comment]
Thanks for your refinement! I will use cvc5 to rerun these benchmarks and remove the incorrect ones.

**Comment by SimpleXiaohu** [comment]
the benchmark is updated

**Comment by hansjoergschurr** [comment]
The benchmarks look great now. Thank you for the submission!

**Comment by kilohsakul** [comment]
Hi guys, this benchmark is slighlty weird, no? Why 3000 variations on the same pattern with the same high counter?

**Comment by SimpleXiaohu** [comment]
> Hi guys, this benchmark is slighlty weird, no? Why 3000 variations on the same pattern with the same high counter?

Hi, Holik, thanks for your comment. It is not weird. For a regex ca*b, we want to generate an attack string like ca{10000,10000}b. This is the intuition, and the actual generating algorithm is more complex.  We use different patterns for almost 600 regexes, so there are 3000 variations.

**Comment by kilohsakul** [comment]
So a string solver is used to generate a word from a language of a regex? 
Satisfiability here is language emptiness of a regex, right?

**Comment by SimpleXiaohu** [comment]
Yes, you are right.

**Pull request merged**
