### PR TITLE
Adding 20240414-funcprobs problems.

### PR DESCRIPTION
**Pull request by MikolasJanota**
Motivated by the recent 10 million dollar AIMO challenge, these SMT
problems targets a problem of finding all functions conforming to a given
specification. This is a popular problem at mathematical competitions and it
brings about a number of challenges, primarily, synthesizing the possible
solutions and proving that no other solutions exist. Often, there are
infinitely many solutions and then the set of solutions has to be captured
symbolically.

### CODE REVIEW

**Comment by hansjoergschurr** [comment]
Than you for the submission!
This problem set looks really interesting (and hard).

Since we want to eventually extract the header files automatically, we try to be somewhat consistent with the `:source` header.

Hence, I would like to change `Encoded by` to `Generated by`.  This might be less accurate, but it is consistent with the other benchmarks.  Some of the other common headers could then be added too.
Overall the header could look something like:
```
Generated by: Mirek Olšák, Mikoláš Janota, Chad E. Brown
Generated on: 2024-04-14
Application: Mathematics challenges involving function synthesis
From a collection by: Vít Musil
Source url: https://prase.cz/library/FunkcionalniRovniceVM/FunkcionalniRovniceVM.pdf
Problem number: [...]
Original source: [...]
```

What do you think?

**Comment by MikolasJanota** [comment]
That  looks good to me. (CCing Mirek)

We're also writing up a report about this, we might be able to put it on
arxiv by the end of the week, is there time to link to it from the files?
If so, what's the best way to do it?

Best
Mikolas

**Comment by hansjoergschurr** [comment]
I think the best place would be a `Publication: ` line in the `:source` header.

I suggest to merge the benchmarks now, and we splice in the `Publication: ` line on our side once you get the report ready.
Like this we can start to prepare the release.

**Comment by hansjoergschurr** [comment]
Thank you! I will merge that now.

**Pull request merged**
