### PR TITLE
Certora benchmark submission 2024

### PR DESCRIPTION
**Pull request by aehyvari**

### CODE REVIEW

**Comment by hansjoergschurr** [comment]
Thank you for submitting the benchmarks.

The data in the folder name schould not use hyphens.  e.g., `2024-04-10-certora/lia-splits/0000.smt2` should be renamed to `20240410-certora/lia-splits/0000.smt2`

**Comment by aehyvari** [comment]
> The data in the folder name schould not use hyphens. e.g., `2024-04-10-certora/lia-splits/0000.smt2` should be renamed to `20240410-certora/lia-splits/0000.smt2`

Ok, I'll fix that, thanks!  The workflow also noticed some duplicates that slipped past me.  I fixed those.

**Comment by aehyvari** [comment]
I think the Dolmen error refers to my file having datatypes... I'll tune the submission a little.

**Comment by hansjoergschurr** [comment]
Looks good!
Those should be included in the upcoming release if nothing unexpected happens.

**Comment by aehyvari** [comment]
Awesome, thank you!  And thanks for maintaining the library!

**Pull request merged**
